"""add_category_and_owner_to_link

Revision ID: 02e0c4e1b9dc
Revises: 12439b2e1310
Create Date: 2026-01-14 10:55:52.543441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02e0c4e1b9dc'
down_revision: Union[str, Sequence[str], None] = '12439b2e1310'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links_to_create',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link')
    )
    op.create_table('links_to_delete',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link')
    )
    op.create_table('link_car',
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.ForeignKeyConstraint(['link_id'], ['links.id'], ),
    sa.PrimaryKeyConstraint('link_id', 'car_id')
    )
    # Додаємо поле як nullable спочатку
    op.add_column('cars', sa.Column('link_path', sa.String(length=150), nullable=True))
    # Оновлюємо існуючі записи з порожнім значенням
    op.execute("UPDATE cars SET link_path = '' WHERE link_path IS NULL")
    # Тепер робимо поле NOT NULL
    op.alter_column('cars', 'link_path', nullable=False)
    op.add_column('links', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('links', sa.Column('owner', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'owner')
    op.drop_column('links', 'category')
    op.drop_column('cars', 'link_path')
    op.drop_table('link_car')
    op.drop_table('links_to_delete')
    op.drop_table('links_to_create')
    # ### end Alembic commands ###
