"""Link add field last process

Revision ID: 12439b2e1310
Revises: 9f174f2b2fce
Create Date: 2026-01-04 16:19:48.324255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12439b2e1310'
down_revision: Union[str, Sequence[str], None] = '9f174f2b2fce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('last_processed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'last_processed_at')
    # ### end Alembic commands ###
