"""add_path_to_images_to_cars

Revision ID: 166846a3ab32
Revises: 0fc47dab5b9a
Create Date: 2026-01-18 16:10:06.259324

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "166846a3ab32"
down_revision: Union[str, Sequence[str], None] = "0fc47dab5b9a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cars", sa.Column("path_to_images", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cars", "path_to_images")
    # ### end Alembic commands ###
