"""add link_to_delete_and_link_to_create

Revision ID: 1b17742843f3
Revises: 3c26ec260c26
Create Date: 2026-01-27 13:09:05.485153

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1b17742843f3"
down_revision: Union[str, Sequence[str], None] = "3c26ec260c26"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "links_to_create", sa.Column("parent_link_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(None, "links_to_create", "links", ["parent_link_id"], ["id"])
    op.add_column(
        "links_to_delete", sa.Column("parent_link_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(None, "links_to_delete", "links", ["parent_link_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "links_to_delete", type_="foreignkey")
    op.drop_column("links_to_delete", "parent_link_id")
    op.drop_constraint(None, "links_to_create", type_="foreignkey")
    op.drop_column("links_to_create", "parent_link_id")
    # ### end Alembic commands ###
