"""add_full_description_to_cars

Revision ID: 3c26ec260c26
Revises: 7ddb8a534a42
Create Date: 2026-01-18 16:53:42.203313

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3c26ec260c26"
down_revision: Union[str, Sequence[str], None] = "7ddb8a534a42"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cars", sa.Column("full_description", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cars", "full_description")
    # ### end Alembic commands ###
