"""add truck_car_id

Revision ID: 793544cb3bc8
Revises: 1cf01ad7448e
Create Date: 2026-01-28 12:02:00.776181

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "793544cb3bc8"
down_revision: Union[str, Sequence[str], None] = "1cf01ad7448e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cars", sa.Column("truck_car_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cars", "truck_car_id")
    # ### end Alembic commands ###
