"""add_model_to_cars

Revision ID: 7ddb8a534a42
Revises: 166846a3ab32
Create Date: 2026-01-18 16:25:30.921879

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7ddb8a534a42"
down_revision: Union[str, Sequence[str], None] = "166846a3ab32"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cars", sa.Column("model", sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cars", "model")
    # ### end Alembic commands ###
