"""remove_car_type_from_cars_add_to_links

Revision ID: c6a0bf5270c8
Revises: 02e0c4e1b9dc
Create Date: 2026-01-14 11:19:58.919877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6a0bf5270c8'
down_revision: Union[str, Sequence[str], None] = '02e0c4e1b9dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Додаємо нове поле car_type в links
    op.add_column('links', sa.Column('car_type', sa.String(length=50), nullable=True))
    
    # Переносимо дані з category в car_type
    op.execute("UPDATE links SET car_type = category WHERE category IS NOT NULL")
    
    # Видаляємо category
    op.drop_column('links', 'category')
    
    # Видаляємо car_type з cars
    op.drop_column('cars', 'car_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('links', 'car_type')
    op.add_column('cars', sa.Column('car_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
